
MOCK_SOURCE = ./lib ./src/a ./src/b ./src/c
MOCK_INCLUDE = ./lib ./src
MOCK_OUTPUT = ./build

MOCK_PATCH = ./src/main.c
MOCK_PSCRIPT = ./scripts/patch.py

include ../../mock.mk

.PHONY: clean

clean: mock_clean
