
import pathlib
import argparse

C_EXTENSIONS = ['.c', '.s', '.cpp']

def find_source(root):
    ''' Find all C source files from the provided root directory.

    Args:
        root (Path): path to the directory to search

    Returns:
        List of found source files.
    '''
    found = []

    for path in pathlib.Path(root).glob('**/*'):
        extension = path.suffix
        if extension in C_EXTENSIONS:
            found.append(path.resolve())

    return found

def main():
    parser = argparse.ArgumentParser("Find sourse files")

    parser.add_argument("source_dirs")
    parser.add_argument("output_dir")
    parser.add_argument("output_file_name")

    args = parser.parse_args()

    output_path = os.path.join(args.output_dir, args.output_file_name)

    with open(output_path, 'w') as output:
        output.write("# Generated by find_mk\n")
        output.write("\n")
        output.write("FIND_OBJS := output/main.o\n")
        output.write("FIND_SRC  := src/main.c\n")
        output.write("\n")
        output.write("output/main.o: src/main.c\n")
        output.write("\t$(CC) -c src/main.c -o output/main.o\n")
        output.write("\n")

if __name__== "__main__":
    main()
