
import os
import pathlib
import argparse

C_EXTENSIONS = ['.c', '.s', '.cpp']

def _fix(path):
    if path[:2] == './':
        path = path[2:]
    return path

def find_source(root, folder="TEST"):
    ''' Find all C source files from the provided root directory.

    Args:
        root (Path): path to the directory to search

    Returns:
        List of found source files.
    '''
    found = []

    for path in pathlib.Path(root).glob('**/*'):
        extension = path.suffix
        if extension in C_EXTENSIONS:
            path = _fix(str(path))
            found.append(path)

    return found

def write_mk(path, srcs, objs):
    with open(path, 'w') as output:
        output.write('\n'.join([
            "# Generated by mockmake python script: mockmake/scripts/source_mk.py",
            '',
            "FIND_OBJS := {}".format(' '.join(['{}'.format(i) for i in objs])),
            "FIND_SRC  := {}".format(' '.join(['{}'.format(i) for i in srcs])),
            '',
            ]))

def main():
    parser = argparse.ArgumentParser("Find source files")

    parser.add_argument("output_file")
    parser.add_argument("source_dirs")
    parser.add_argument("patch_files")

    args = parser.parse_args()

    source_dirs = [i.strip() for i in args.source_dirs.split()]

    all_sources = []
    for some_dir in source_dirs:
        if some_dir:
            all_sources.extend(find_source(some_dir))

    patch_files = []
    patch_source_files = []
    patch_object_files = []
    for patch_file in args.patch_files.split():
        patch_file = _fix(patch_file)
        patch_files.append(patch_file)

        name, _ = os.path.splitext(patch_file)

        source_name = name + '.patch.c'
        patch_source_files.append(os.path.join('$(MOCK_OUTPUT)', source_name))

        object_name = name + '.patch.o'
        patch_object_files.append(os.path.join('$(MOCK_OUTPUT)', object_name))

    all_sources = [i for i in all_sources if i not in patch_files]

    all_objects = []
    for i in all_sources:
        name, _ = os.path.splitext(i)
        name += '.o'
        obj = os.path.join('$(MOCK_OUTPUT)', name)

        all_objects.append(obj)

    all_sources.extend(patch_source_files)
    all_objects.extend(patch_object_files)

    # output_path = os.path.join(args.output_file)
    write_mk(args.output_file, all_sources, all_objects)

if __name__== "__main__":
    main()
