name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Python and Test
      run: |
        python -m venv python-env
        source python-env/bin/activate
        python -m pip install pytest
        make test
